version: "3.8"

services:

  accounts:
    image: banksystem/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - banksystem-network
    
  loans:
    image: banksystem/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - banksystem-network
    
  cards:
    image: banksystem/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - banksystem-network
    
networks:
  banksystem-network: