version: "3.8"

services:

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
     - banksystem

  configserver:
    image: jackieung451/banksystem-configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - banksystem
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
     
  eurekaserver:
    image: jackieung451/banksystem-eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - banksystem
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  accounts:
    image: jackieung451/banksystem-accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - banksystem
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  
  loans:
    image: jackieung451/banksystem-loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - banksystem
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    
  cards:
    image: jackieung451/banksystem-cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - banksystem
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  gatewayserver:
        image: jackieung451/banksystem-gatewayserver:latest
        mem_limit: 700m
        ports:
          - "8072:8072"
        networks:
          - banksystem
        depends_on:
          - configserver
          - eurekaserver
          - cards
          - loans
          - accounts
        deploy:
          restart_policy:
            condition: on-failure
            delay: 45s
            max_attempts: 3
            window: 180s
        environment:
          SPRING_PROFILES_ACTIVE: default
          SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
          SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

   
networks:
  banksystem:
